namespace NiksoftCore.DataModel
{
    public class SiscoRecord
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CDRRecordType { get; set; }
        public string GCIDCallManagerId { get; set; }
        public string GCIDCallId { get; set; }
        public string OrigLegCallIdentifier { get; set; }
        public long DateTimeOrigination { get; set; }
        public string OrigNodeId { get; set; }
        public string OrigSpan { get; set; }
        public string OrigIpAddr { get; set; }
        public string CPartyNumber { get; set; }
        public string CPartyUCLoginUserID { get; set; }
        public string OrigCauseLocation { get; set; }
        public string OrigCauseValue { get; set; }
        public string OrigPrecedenceLevel { get; set; }
        public string OrigMediaTransportAIP { get; set; }
        public string OrigMediaTransportAPort { get; set; }
        public string OrigMediaCapPayloadCapability { get; set; }
        public string OrigMediaCapMaxFramesPerPacket { get; set; }
        public string OrigMediaCapG723BitRate { get; set; }
        public string OrigVideoCapCodec { get; set; }
        public string OrigVideoCapBandwidth { get; set; }
        public string OrigVideoCapResolution { get; set; }
        public string OrigVideoTransportAIP { get; set; }
        public string OrigVideoTransportAPort { get; set; }
        public string OrigRSVPAudioStat { get; set; }
        public string OrigRSVPVideoStat { get; set; }
        public string DestLegIdentifier { get; set; }
        public string DestNodeId { get; set; }
        public string DestSpan { get; set; }
        public string DestIpAddr { get; set; }
        public string OriginalCalledPartyNumber { get; set; }
        public string FinalCalledPartyNumber { get; set; }
        public string FinalCalledPartyUnicodeLUID { get; set; }
        public string DestCauseLocation { get; set; }
        public string DestCauseValue { get; set; }
        public string DestPrecedenceLevel { get; set; }
        public string DestMediaTransportAIP { get; set; }
        public string DestMediaTransportAPort { get; set; }
        public string DestMediaCapPayloadCapability { get; set; }
        public string DestMediaCapMaxFramesPerPacket { get; set; }
        public string DestMediaCapG723BitRate { get; set; }
        public string DestVideoCapCodec { get; set; }
        public string DestVideoCapBandwidth { get; set; }
        public string DestVideoCapResolution { get; set; }
        public string DestVideoTransportAIP { get; set; }
        public string DestVideoTransportAPort { get; set; }
        public string DestRSVPAudioStat { get; set; }
        public string DestRSVPVideoStat { get; set; }
        public long DateTimeConnect { get; set; }
        public long DateTimeDisconnect { get; set; }
        public string LastRedirectDn { get; set; }
        public string Pkid { get; set; }
        public string OrigCalledPartyNumPartition { get; set; }
        public string CallingPartyNumPartition { get; set; }
        public string FinalCalledPartyNumPartition { get; set; }
        public string LastRedirectDnPartition { get; set; }
        public string Duration { get; set; }
        public string OrigDeviceName { get; set; }
        public string DestDeviceName { get; set; }
        public string OrigCallTerminOnBehalfOf { get; set; }
        public string DestCallTerminOnBehalfOf { get; set; }
        public string OrigCallPartyRedirOnBehalfOf { get; set; }
        public string LastRedirOnBehalfOf { get; set; }
        public string OrigCalledPartyRedirReason { get; set; }
        public string LastRedirReason { get; set; }
        public string DestConversationId { get; set; }
        public string GlobalCallIdClusterID { get; set; }
        public string JoinOnBehalfOf { get; set; }
        public string Comment { get; set; }
        public string AuthCodeDescription { get; set; }
        public string AuthorizationLevel { get; set; }
        public string ClientMatterCode { get; set; }
        public string OrigDTMFMethod { get; set; }
        public string DestDTMFMethod { get; set; }
        public string CallSecuredStatus { get; set; }
        public string OrigConversationId { get; set; }
        public string OrigMediaCapBandwidth { get; set; }
        public string DestMediaCapBandwidth { get; set; }
        public string AuthorizationCodeValue { get; set; }
        public string OutpulsedCallingPartyNum { get; set; }
        public string OutpulsedCalledPartyNum { get; set; }
        public string OrigIpv4v6Addr { get; set; }
        public string DestIpv4v6Addr { get; set; }
        public string OrigVideoCapCodecChl2 { get; set; }
        public string OrigVideoCapBandwidthChl2 { get; set; }
        public string OrigVideoCapResolutionChl2 { get; set; }
        public string OrigVideoTransportAIPChl2 { get; set; }
        public string OrigVideoTransportAPortChl2 { get; set; }
        public string OrigVideoChannelRoleChl2 { get; set; }
        public string DestVideoCapCodecChl2 { get; set; }
        public string DestVideoCapBandwidthChl2 { get; set; }
        public string DestVideoCapResolutionChl2 { get; set; }
        public string DestVideoTransportAIPChl2 { get; set; }
        public string DestVideoTransportAPortChl2 { get; set; }
        public string DestVideoChannelRoleChl2 { get; set; }
        public int IncomingProtocolID { get; set; }
        public string IncomingProtocolCallRef { get; set; }
        public int OutgoingProtocolID { get; set; }
        public string OutgoingProtocolCallRef { get; set; }
        public string CurrentRoutingReason { get; set; }
        public string OrigRoutingReason { get; set; }
        public string LastRedirectingRoutingReason { get; set; }
        public string HuntPilotDN { get; set; }
        public string HuntPilotPartition { get; set; }
        public string CalledPartyPatternUsage { get; set; }
        public string OutpulsedOriginalCalledPartyNum { get; set; }
        public string OutpulsedLastRedirectingNum { get; set; }
        public string WasCallQueued { get; set; }
        public string TotalWaitTimeInQueue { get; set; }
        public string CallingPartyNumUri { get; set; }
        public string OriginalCalledPartyNumUri { get; set; }
        public string FinalCalledPartyNumUri { get; set; }
        public string LastRedirectDnUri { get; set; }
        public string MobileCallingPartyNum { get; set; }
        public string FinalMobileCalledPartyNum { get; set; }
        public string OrigMobileDeviceName { get; set; }
        public string DestMobileDeviceName { get; set; }
        public string OrigMobileCallDuration { get; set; }
        public string DestMobileCallDuration { get; set; }
        public string MobileCallType { get; set; }
        public string OrigCalledPartyPattern { get; set; }
        public string FinalCalledPartyPattern { get; set; }
        public string LastRedirectingPartyPattern { get; set; }
        public string HuntPilotPattern { get; set; }

        public virtual User User { get; set; }
    }
}
